---
version: "2"

services:
    odoo:
        image: laslabs/odoo-medical:10.0.0.1-dev
        build:
            args:
                PGDATABASE: devel
                # To aggregate in development, use `setup-devel.yaml`
                AGGREGATE: "true"
                # No need for this in development
                PYTHONOPTIMIZE: 0
                PIP_INSTALL_ODOO: "false"
                CLEAN: "false"
                COMPILE: "false"
                # You want demo data for development
                WITHOUT_DEMO: "false"
                PGUSER: "odoo"
                PGPASSWORD: "odoo"
        ports:
            - "8069"
            - "8072"
            - "6899"
        tty: true
        volumes:
            - filestore$ODOO_MAJOR:/var/lib/odoo
            - ./odoo/custom:/opt/odoo/custom:ro,z
        networks:
            default:
                aliases:
                    # For `https` service
                    - www
        depends_on:
            - db
        # XXX Odoo v8 has no `--dev` mode; Odoo v9 has no `all` parameter
        command: odoo --workers 0 --dev all

    db:
        image: postgres:9.4-alpine
        environment:
            POSTGRES_USER: "odoo"
            POSTGRES_PASSWORD: "odoo"
        volumes:
            - db10:/var/lib/postgresql/data

volumes:
    # XXX Odoo volume names must match $ODOO_MAJOR for quick branch switching
    filestore10:
        driver: rancher-nfs
    db10:
        driver: rancher-nfs
