---
version: "2"

services:
    odoo:
        image: laslabs/odoo-medical:10.0.0.1-dev
        build:
            context: ./odoo
            args:
                PGDATABASE: ${db_name}
                AGGREGATE: ${aggregate}
                PYTHONOPTIMIZE: ${python_optimize}
                PIP_INSTALL_ODOO: ${odoo_pip}
                CLEAN: ${do_clean}
                COMPILE: ${do_compile}
                WITHOUT_DEMO: ${odoo_demo}
                PGUSER: ${db_user}
                PGPASSWORD: ${db_pass}
        ports:
            - "8069"
            - "8072"
        tty: true
        volumes:
            - odoo-filestore:/var/lib/odoo
            - odoo-custom:/opt/odoo/custom:ro,z
        depends_on:
            - db
        labels:
            traefik.domain: ${domain}
            traefik.port: ${port}
            traefik.enable: ${do_proxy}
    db:
        image: postgres:${db_version}-alpine
        environment:
            POSTGRES_USER: ${db_user}
            POSTGRES_PASSWORD: ${db_pass}
        volumes:
            - odoo-db:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    odoo-custom:
        driver: rancher-nfs
    odoo-filestore:
        driver: rancher-nfs
    odoo-db:
        driver: rancher-nfs
