version: "2"

catalog:
  name: Odoo Medical
  version: "v10.0.0.1"
  description: "Odoo for Medical Professionals"
  uuid: vertical-medical-dev-0
  minimum_rancher_version: v1.0.0
  questions:

    - variable: domain
      description: "Root domain that application will be served on (as ${application}.${stack}.${domain}) - only used if proxy is enabled."
      label: "Domain"
      required: true
      default: "laslabs.laslabs.io"
      type: "string"

    - variable: odoo_version
      description: "Odoo version"
      label: "Odoo Version"
      required: true
      default: "10.0"
      type: "string"
    - variable: odoo_pass
      description: "Odoo administrator default password"
      label: "Admin Pass"
      required: true
      default: "admin"
      type: "password"

    - variable: python_optimize
      description: "Which PYTHONOPTIMIZE level to use."
      label: "Python Optimize"
      default: 2
      type: "int"

    - variable: db_version
      description: "Postgres version"
      label: "DB Version"
      required: true
      default: "9.6"
      type: "enum"
      options:
       - "9.6"
       - "9.5"
       - "9.4"
       - "9.3"
    - variable: db_name
      description: "Name of database"
      label: "DB Name"
      required: true
      default: "odoo"
      type: "string"
    - variable: db_user
      description: "User to access database with"
      label: "DB User"
      required: true
      default: "odoo"
      type: "string"
    - variable: db_pass
      description: "Password for database user"
      label: "DB Pass"
      required: true
      default: "odoo"
      type: "password"

    - variable: aggregate
      description: "Aggregate code repositories"
      label: "Aggregate"
      default: true
      type: "boolean"
    - variable: odoo_demo
      description: "Enable Odoo demo data"
      label: "Demo?"
      default: false
      type: "boolean"
    - variable: odoo_pip
      description: "PIP install Odoo (disable this for dev)"
      label: "PIP Install Odoo"
      default: true
      type: "boolean"
    - variable: do_clean
      description: "Clean up garbage (disable this for dev)"
      label: "Clean?"
      default: true
      type: "boolean"
    - variable: do_compile
      description: "Compile Python code (disable this for dev)"
      label: "Compile?"
      default: true
      type: "boolean"
    - variable: do_proxy
      description: "Should the Traefik proxy be used for this instance?"
      label: "Proxy?"
      default: true
      type: "boolean"



odoo:
  scale: 1
  health_check:
    port: 8069
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2
