# XXX Base version must match $ODOO_VERSION in .env file
FROM tecnativa/odoo-base:10.0
MAINTAINER LasLabs Inc <support@laslabs.com>

# Metadata
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="Odoo Medical (Dev)" \
      org.label-schema.description="Provides a dev environment for Odoo Medical." \
      org.label-schema.url="https://laslabs.com/" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="https://github.com/LasLabs/docker-odoo-scaffolds" \
      org.label-schema.vendor="LasLabs Inc." \
      org.label-schema.version=$VERSION \
      org.label-schema.schema-version="1.0"
